= Notifications
- CARMS data-change-notification methods, action-notifications, compile-time opt-in

Hist notifications only require you to add a method to your tracked class:

[[ Example ]] 

Note the path [[ IDK something about paths]]

[[ Example of Paths?]]

Hist supports the "C.A.R.M.S." notifications - change, add, remove, move, and selection-update. Change is applicable to [all? non-container?] fields while add, remove, move, and selection update is only applicable to containers.

[[ Change Examples ]]
[[ Add Examples ]]
[[ Remove Examples ]]
[[ Move Examples ]]
[[ Selection Update Examples ]]

Implementation note:
Observe that template argument where you repeated your class name: [[ Picture of template argument ]]

This is here so that the hist library can check, at compile time, whether a given method is present on your object, and if so add the code to call it from the ops for that given path and makes it possible to call your notification method directly without polymorphism -- this way the cost of notifications is minimal, and if you aren't using a notification (at all or on a particular field) you pay nothing!
